# Generated by Django 2.2.17 on 2020-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youths", "0002_add_temporary_profile_access_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youthprofile",
            name="approval_token",
            field=models.CharField(blank=True, editable=False, max_length=36),
        ),
    ]
