include:
    - project: "city-of-helsinki/kuva/ci-cd-config/ci-configuration"
      ref: v2
      file: "/.gitlab-ci-template.yml"

variables:
    APP_MIGRATE_COMMAND: /app/.prod/on_deploy.sh

build:
    extends: .build

review:
    variables:
        K8S_SECRET_ALLOWED_HOSTS: "*"
        K8S_SECRET_DEBUG: 1
        K8S_SECRET_ADMIN_USER_PASSWORD: "admin"
        K8S_SECRET_GDPR_API_ENABLED: 1
        K8S_SECRET_SENTRY_DSN: "$GL_SENTRY_DSN"
        K8S_SECRET_SENTRY_ENVIRONMENT: "test"
        K8S_SECRET_VERSION: "$CI_COMMIT_SHORT_SHA"
        K8S_SECRET_ENABLE_GRAPHIQL: 1
        K8S_SECRET_TOKEN_AUTH_ACCEPTED_AUDIENCE: "https://api.hel.fi/auth/jassariapi"
        K8S_SECRET_TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX: "jassariapi"
        K8S_SECRET_TOKEN_AUTH_AUTHSERVER_URL: "https://api.hel.fi/sso-test"
        K8S_SECRET_TOKEN_AUTH_REQUIRE_SCOPE: 1
        K8S_SECRET_OIDC_CLIENT_SECRET: "$GL_QA_OIDC_CLIENT_SECRET"
        K8S_SECRET_HELSINKI_PROFILE_AUTH_SCOPE: "https://api.hel.fi/auth/helsinkiprofile"
        K8S_SECRET_HELSINKI_PROFILE_AUTH_CALLBACK_URL: "https://jassari.test.kuva.hel.ninja/callback"
        K8S_SECRET_HELSINKI_PROFILE_API_URL: "https://profiili-api.test.kuva.hel.ninja/graphql/"
        K8S_SECRET_MAIL_MAILGUN_KEY: "$GL_MAILGUN_API_KEY"
        K8S_SECRET_MAIL_MAILGUN_DOMAIN: "mail.hel.ninja"
        K8S_SECRET_MAIL_MAILGUN_API: "https://api.eu.mailgun.net/v3"
        K8S_SECRET_MAILER_EMAIL_BACKEND: "anymail.backends.mailgun.EmailBackend"
        K8S_SECRET_DEFAULT_FROM_EMAIL: "no-reply@hel.ninja"
        K8S_SECRET_AUDIT_LOGGING_ENABLED: 1
        POSTGRES_IMAGE: "docker.io/andersinnovations/postgis:11-bitnami"

staging:
    only:
        refs:
            - develop
    variables:
        K8S_SECRET_ALLOWED_HOSTS: "*"
        K8S_SECRET_DEBUG: 0
        K8S_SECRET_SECRET_KEY: "$GL_QA_DJANGO_SECRET_KEY"
        K8S_SECRET_GDPR_API_ENABLED: 1
        K8S_SECRET_SENTRY_DSN: "$GL_SENTRY_DSN"
        K8S_SECRET_SENTRY_ENVIRONMENT: "test"
        K8S_SECRET_SKIP_DATABASE_CHECK: 1
        K8S_SECRET_VERSION: "$CI_COMMIT_SHORT_SHA"
        K8S_SECRET_ENABLE_GRAPHIQL: 1
        K8S_SECRET_TOKEN_AUTH_ACCEPTED_AUDIENCE: "https://api.hel.fi/auth/jassariapi"
        K8S_SECRET_TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX: "jassariapi"
        K8S_SECRET_TOKEN_AUTH_AUTHSERVER_URL: "https://api.hel.fi/sso-test"
        K8S_SECRET_TOKEN_AUTH_REQUIRE_SCOPE: 1
        K8S_SECRET_OIDC_CLIENT_SECRET: "$GL_QA_OIDC_CLIENT_SECRET"
        K8S_SECRET_HELSINKI_PROFILE_AUTH_SCOPE: "https://api.hel.fi/auth/helsinkiprofile"
        K8S_SECRET_HELSINKI_PROFILE_AUTH_CALLBACK_URL: "https://jassari.test.kuva.hel.ninja/callback"
        K8S_SECRET_HELSINKI_PROFILE_API_URL: "https://profiili-api.test.kuva.hel.ninja/graphql/"
        K8S_SECRET_MAIL_MAILGUN_KEY: "$GL_MAILGUN_API_KEY"
        K8S_SECRET_MAIL_MAILGUN_DOMAIN: "mail.hel.ninja"
        K8S_SECRET_MAIL_MAILGUN_API: "https://api.eu.mailgun.net/v3"
        K8S_SECRET_MAILER_EMAIL_BACKEND: "anymail.backends.mailgun.EmailBackend"
        K8S_SECRET_DEFAULT_FROM_EMAIL: "no-reply@hel.ninja"
        K8S_SECRET_AUDIT_LOGGING_ENABLED: 1
#        K8S_SECRET_SESSION_COOKIE_SECURE: 1


production:
    variables:
        K8S_SECRET_ALLOWED_HOSTS: "*"
        K8S_SECRET_DEBUG: 0
        K8S_SECRET_SECRET_KEY: "$GL_STABLE_DJANGO_SECRET_KEY"
        K8S_SECRET_SENTRY_DSN: "$GL_SENTRY_DSN"
        K8S_SECRET_SENTRY_ENVIRONMENT: "production"
        K8S_SECRET_SKIP_DATABASE_CHECK: 1
        K8S_SECRET_VERSION: "$CI_COMMIT_SHORT_SHA"
        K8S_SECRET_TOKEN_AUTH_ACCEPTED_AUDIENCE: "https://api.hel.fi/auth/jassariapi"
        K8S_SECRET_TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX: "jassariapi"
        K8S_SECRET_TOKEN_AUTH_AUTHSERVER_URL: "https://api.hel.fi/sso"
        K8S_SECRET_TOKEN_AUTH_REQUIRE_SCOPE: 1
        K8S_SECRET_OIDC_CLIENT_SECRET: "$GL_STABLE_OIDC_CLIENT_SECRET"
        K8S_SECRET_HELSINKI_PROFILE_AUTH_SCOPE: "https://api.hel.fi/auth/helsinkiprofile"
        K8S_SECRET_HELSINKI_PROFILE_AUTH_CALLBACK_URL: "https://jassari.hel.fi/callback"
        K8S_SECRET_HELSINKI_PROFILE_API_URL: "https://api.hel.fi/profiili/graphql/"
        K8S_SECRET_MAIL_MAILGUN_KEY: "$GL_MAILGUN_API_KEY"
        K8S_SECRET_MAIL_MAILGUN_DOMAIN: "mail.hel.ninja"
        K8S_SECRET_MAIL_MAILGUN_API: "https://api.eu.mailgun.net/v3"
        K8S_SECRET_MAILER_EMAIL_BACKEND: "anymail.backends.mailgun.EmailBackend"
        K8S_SECRET_DEFAULT_FROM_EMAIL: "no-reply@hel.fi"
        K8S_SECRET_AUDIT_LOGGING_ENABLED: 1
#        K8S_SECRET_FORCE_SCRIPT_NAME: "/profiili"
#        K8S_SECRET_MEDIA_URL: "/profiili/media/"
#        K8S_SECRET_STATIC_URL: "/profiili/static/"
#        K8S_SECRET_CSRF_COOKIE_NAME: "profiili-prod-csrftoken"
#        K8S_SECRET_CSRF_COOKIE_PATH: "/profiili/"
#        K8S_SECRET_CSRF_COOKIE_SECURE: 1
#        K8S_SECRET_SESSION_COOKIE_NAME: "profiili-prod-sessionid"
#        K8S_SECRET_SESSION_COOKIE_PATH: "/profiili/"
#        K8S_SECRET_SESSION_COOKIE_SECURE: 1
#        K8S_SECRET_USE_X_FORWARDED_HOST: 1
#        K8S_SECRET_CSRF_TRUSTED_ORIGINS: "api.hel.fi"
