# Common errors
API_NOT_IMPLEMENTED_ERROR = "API_NOT_IMPLEMENTED_ERROR"
GENERAL_ERROR = "GENERAL_ERROR"
INVALID_EMAIL_FORMAT_ERROR = "INVALID_EMAIL_FORMAT"
OBJECT_DOES_NOT_EXIST_ERROR = "OBJECT_DOES_NOT_EXIST_ERROR"
PERMISSION_DENIED_ERROR = "PERMISSION_DENIED_ERROR"
PROFILE_HAS_NO_PRIMARY_EMAIL_ERROR = "PROFILE_HAS_NO_PRIMARY_EMAIL_ERROR"
PROFILE_DOES_NOT_EXIST_ERROR = "PROFILE_DOES_NOT_EXIST_ERROR"
TOKEN_EXPIRED_ERROR = "TOKEN_EXPIRED_ERROR"
PROFILE_API_ERROR = "PROFILE_API_ERROR"

# Profile specific errors
PROFILE_MUST_HAVE_ONE_PRIMARY_EMAIL = "PROFILE_MUST_HAVE_ONE_PRIMARY_EMAIL"
